package landing

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/brendandebeasi/tabby/pkg/paths"
)

// ConfigFile is the landing page's data file, relative to the tabby config
// directory. It is generated by the tabby-landing skill, which is where the
// judgement about what belongs on the page lives. The renderer only reads it.
const ConfigFile = "landing.yaml"

// Entry is one launchable target.
//
// color, icon, and group are not invented by the landing page. Local entries
// inherit them from ~/.local/state/tabby/cwd-colors.json and ssh entries from
// the first matching remote_hosts glob in config.yaml. Only Rank is new: it is
// an ordinal, 1 = most used, derived from zoxide scores and ssh history counts.
type Entry struct {
	Label string `yaml:"label"`
	Kind  string `yaml:"kind"`
	Dir   string `yaml:"dir,omitempty"`
	Host  string `yaml:"host,omitempty"`
	Color string `yaml:"color,omitempty"`
	Icon  string `yaml:"icon,omitempty"`
	Group string `yaml:"group,omitempty"`
	Rank  int    `yaml:"rank"`
}

// Config is the whole landing.yaml document.
type Config struct {
	Version    int     `yaml:"version"`
	SourceHost string  `yaml:"source_host,omitempty"`
	Generated  string  `yaml:"generated,omitempty"`
	Entries    []Entry `yaml:"entries"`
}

const (
	kindLocal = "local"
	kindSSH   = "ssh"
)

// ConfigPath returns the absolute path to landing.yaml.
func ConfigPath() string {
	return filepath.Join(paths.ConfigDir(), ConfigFile)
}

// Load reads and validates landing.yaml.
//
// A missing file is reported as os.ErrNotExist so the caller can fall through
// to a plain shell with a hint. A new tab must never fail to open because the
// landing page has nothing to show.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	dec := yaml.NewDecoder(strings.NewReader(string(data)))
	dec.KnownFields(true)
	if err := dec.Decode(&cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	kept := cfg.Entries[:0]
	for _, e := range cfg.Entries {
		if err := e.validate(); err != nil {
			continue
		}
		kept = append(kept, e)
	}
	cfg.Entries = kept
	sort.SliceStable(cfg.Entries, func(i, j int) bool {
		return cfg.Entries[i].Rank < cfg.Entries[j].Rank
	})
	return &cfg, nil
}

func (e Entry) validate() error {
	if strings.TrimSpace(e.Label) == "" {
		return fmt.Errorf("entry has no label")
	}
	switch e.Kind {
	case kindLocal:
		if strings.TrimSpace(e.Dir) == "" {
			return fmt.Errorf("%s: local entry has no dir", e.Label)
		}
	case kindSSH:
		if strings.TrimSpace(e.Host) == "" {
			return fmt.Errorf("%s: ssh entry has no host", e.Label)
		}
	default:
		return fmt.Errorf("%s: unknown kind %q", e.Label, e.Kind)
	}
	return nil
}

// Target is the entry's destination shown next to its label.
func (e Entry) Target() string {
	if e.Kind == kindSSH {
		return e.Host
	}
	return e.Dir
}

// Command is the shell command that lands you in this entry.
//
// The command is printed on stdout for the calling shell to eval rather than
// executed here. Running it in the pane's own interactive shell is what keeps
// tmux reporting pane_current_command as "ssh" for remote entries, which the
// daemon needs for the remote icon and host color.
func (e Entry) Command() string {
	if e.Kind == kindSSH {
		return "ssh " + shellQuote(e.Host)
	}
	return "cd " + shellQuote(expandHome(e.Dir))
}

func expandHome(p string) string {
	if p != "~" && !strings.HasPrefix(p, "~/") {
		return p
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return p
	}
	if p == "~" {
		return home
	}
	return filepath.Join(home, p[2:])
}

// shellQuote wraps s in single quotes, escaping any it contains, so a path
// with spaces or shell metacharacters survives the eval intact.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// group is a run of entries sharing a Group value, in display order.
type group struct {
	name    string
	entries []Entry
}

// groupEntries buckets entries by Group, ordering the buckets by their best
// (lowest) rank so the group you reach for most sits first. Ungrouped entries
// form their own leading bucket with an empty name and no header.
func groupEntries(entries []Entry) []group {
	order := []string{}
	byName := map[string][]Entry{}
	for _, e := range entries {
		if _, ok := byName[e.Group]; !ok {
			order = append(order, e.Group)
		}
		byName[e.Group] = append(byName[e.Group], e)
	}
	// entries arrive rank-sorted, so the first occurrence of each group name
	// is already its best rank and `order` is already the right sequence.
	out := make([]group, 0, len(order))
	for _, name := range order {
		out = append(out, group{name: name, entries: byName[name]})
	}
	return out
}

// applyFilter keeps entries whose label, target, or group contains the filter,
// case-insensitively. Substring rather than prefix: you reach for these by the
// memorable part of the name, which is often not the first word.
func applyFilter(entries []Entry, filter string) []Entry {
	filter = strings.ToLower(strings.TrimSpace(filter))
	if filter == "" {
		return entries
	}
	var out []Entry
	for _, e := range entries {
		hay := strings.ToLower(e.Label + " " + e.Target() + " " + e.Group)
		if strings.Contains(hay, filter) {
			out = append(out, e)
		}
	}
	return out
}
